interface IHTTP_CONFIG {
  STATUS_CODE: {
    SUCCESSFUL: 200,
    METHOD_NOT_ALLOWED: 405,
    INCORRECT_CREDENTIALS: 401,
    USER_NOT_FOUND: 404,
    FIELDS_REQUIRED: 400,
    CONFLICT_TO_CREATE_USER: 409,
  },

  METHODS: {
    POST: 'POST',
    UPDATE: 'UPDATE',
    GET: 'GET',
    DELETE: 'DELETE'
  }
}

export const HTTP: IHTTP_CONFIG = {
  STATUS_CODE: {
    SUCCESSFUL: 200,
    METHOD_NOT_ALLOWED: 405,
    INCORRECT_CREDENTIALS: 401,
    USER_NOT_FOUND: 404,
    FIELDS_REQUIRED: 400,
    CONFLICT_TO_CREATE_USER: 409
  },
  METHODS: {
    POST: 'POST',
    UPDATE: 'UPDATE',
    GET: 'GET',
    DELETE: 'DELETE'
  }
}
