export interface IROLES {
  CUSTOMER: 'CUSTOMER',
  MERCHANT: 'MERCHANT',
  DRIVER: 'DRIVER',
  AGENT: 'AGENT',
  ADMIN: 'ADMIN',
  INTEGROUScUSTOMER: 'INTEGROUScUSTOMER',
  INTEGROUSaSSOCIATE: 'INTEGROUSaSSOCIATE'
}

export type TROLE =
  IROLES['CUSTOMER'] |
  IROLES['MERCHANT'] |
  IROLES['DRIVER'] |
  IROLES['AGENT'] |
  IROLES['ADMIN'] |
  IROLES['INTEGROUScUSTOMER'] |
  IROLES['INTEGROUSaSSOCIATE']
