export { SignUpDriverForm } from './FormByRole/Driver'
export { SignUpCustomerForm } from './FormByRole/Customer'
export { SignUpAgentForm } from './FormByRole/Agent'
export { SignUpIntegrousCustomerForm } from './FormByRole/SignUpIntegrousCustomerForm'
export { SignUpIntegrousAssociateForm } from './FormByRole/SignUpIntegrousAssociateForm'
